---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "scancodeio.fullname" . }}-worker
  labels:
    {{- include "scancodeio.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  serviceName: {{ include "scancodeio.fullname" . }}-worker
  selector:
    matchLabels:
      {{- include "scancodeio.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        tag: "{{ .Values.image.tag }}"
      labels:
        {{- include "scancodeio.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "scancodeio.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      initContainers:
        - name: wait-for-postgres
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            - name: SCANCODEIO_DB_NAME
              valueFrom:
                secretKeyRef:
                  key: database
                  name: scancode-secret
            - name: SCANCODEIO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: scancode-secret
            - name: SCANCODEIO_DB_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: scancode-secret
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: SECRET_KEY
                  name: scancode-secret
            - name: SCANCODEIO_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: SCANCODEIO_REDIS_PASSWORD
                  name: scancode-secret
          envFrom:
            - configMapRef:
                name: {{ include "scancodeio.fullname" . }}-scancode-env
          command: ['./manage.py', 'wait_for_database']
      containers:
        - name: {{ .Chart.Name }}
          args:
            - ./manage.py
            - rqworker
            - --worker-class
            - scancodeio.worker.ScanCodeIOWorker
            - --queue-class
            - scancodeio.worker.ScanCodeIOQueue
            - --verbosity
            - "2"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          #TODO: livenessprobe, readinessprobe, resources
          env:
            - name: SCANCODEIO_DB_NAME
              valueFrom:
                secretKeyRef:
                  key: database
                  name: scancode-secret
            - name: SCANCODEIO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: scancode-secret
            - name: SCANCODEIO_DB_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: scancode-secret
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: SECRET_KEY
                  name: scancode-secret
            - name: SCANCODEIO_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: SCANCODEIO_REDIS_PASSWORD
                  name: scancode-secret
          envFrom:
            - configMapRef:
                name: {{ include "scancodeio.fullname" . }}-scancode-env
          volumeMounts:
            - mountPath: /etc/scancodeio/
              name: {{ include "scancodeio.fullname" . }}-worker-claim
            - mountPath: /var/scancodeio/workspace/
              name: {{ include "scancodeio.fullname" . }}-workspace-claim
      restartPolicy: Always
      volumes:
        - name: {{ include "scancodeio.fullname" . }}-worker-claim
          persistentVolumeClaim:
            claimName: {{ include "scancodeio.fullname" . }}-worker-claim
        - name: {{ include "scancodeio.fullname" . }}-workspace-claim
          persistentVolumeClaim:
            claimName: {{ include "scancodeio.fullname" . }}-workspace-claim
    {{- with .Values.web.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.web.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.web.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
