---
# Default values for scancodeio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# For FQDN resolving of the controller service. Change this value to match your existing configuration.
# ref: https://github.com/kubernetes/dns/blob/master/docs/specification.md
clusterZone: "cluster.local"

scancodeDatabase: scancode-db
scancodeUsername: scancode-user
# change default password
scancodePassword: scancode-pwd
# change default password
scancodePostgresPassword: scancode-admin-pwd
# change default secret key
scancodeSECRET_KEY: ""
# change default password
scancodeSCANCODEIO_REDIS_PASSWORD: scancode-redis-pwd

env:
  plain: {}
  secret: {}

image:
  repository: aalexanderr/scancodeio
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v30.2.0-onap2"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

web:
  replicaCount: 1
  port: 8000
  # We usually recommend not to specify default resources and to leave this
  # as a conscious choice for the user. This also increases chances charts
  # run on environments with little resources, such as Minikube.
  # If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary,
  # and remove the curly braces after 'resources:'.
  resources: {}
    # limits:
    #   cpu: 1000m
    #   memory: 512Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  livenessProbe:
    failureThreshold: 5
    initialDelaySeconds: 5
    timeoutSeconds: 2
  readinessProbe:
    failureThreshold: 10
    initialDelaySeconds: 5
    timeoutSeconds: 2
  nodeSelector: {}
  tolerations: []
  affinity: {}
  service:
    type: ClusterIP
    port: 8080


worker:
  replicaCount: 1
  # We usually recommend not to specify default resources and to leave this
  # as a conscious choice for the user. This also increases chances charts
  # run on environments with little resources, such as Minikube.
  # If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary,
  # and remove the curly braces after 'resources:'.
  resources: {}
    # limits:
    #   cpu: 900m
    #   memory: 768Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}


serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname
  # template
  name: ""

securityContext: {}
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# allowPrivilegeEscalation: false
# runAsNonRoot: true
# runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


postgresql:
  # TODO: mention what should be set from SCIO side of chart for own deployment
  enabled: true
  auth:
    username: scancode-user
    database: scancode-db
    existingSecret: scancode-secret

redis:
  # TODO: mention what should be set from SCIO side of chart for own deployment
  enabled: true
  architecture: standalone
  auth:
    enabled: true
    existingSecret: scancode-secret
    existingSecretPasswordKey: SCANCODEIO_REDIS_PASSWORD

nginx:
  service:
    type: NodePort
  extraVolumes:
    - name: "{{ .Release.Name }}-staticsite"
      persistentVolumeClaim:
        claimName: "{{ .Release.Name }}-staticsite"
  extraVolumeMounts:
    - mountPath: /static
      name: "{{ .Release.Name }}-staticsite"

  # TODO: switch to managestatic
  initContainers:
    - name: populate-static
      image: eeproton/scancodeio_web
      command: ['/bin/sh']
      args:
        - '-c'
        - "find /static/ -mindepth 1 -maxdepth 1 -type d -delete && \
          mkdir -p /static/scancodeio /static/scancodeio-static && \
          cp -r /var/scancodeio/static/ /static/scancodeio && \
          cp -r /usr/local/lib/python3.9/site-packages/rest_framework/static/ \
          /static/scancodeio-static && \
          cp -r \
          /usr/local/lib/python3.9/site-packages/django/contrib/admin/static/ \
          /static/scancodeio-static"
      volumeMounts:
        - mountPath: /static
          name: "{{ .Release.Name }}-staticsite"

  existingServerBlockConfigmap: scancodeio-nginx
