apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scancodeio.fullname" . }}-web
  labels:
    {{- include "scancodeio.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      {{- include "scancodeio.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        tag: {{ .Values.image.tag | quote }}
      labels:
        {{- include "scancodeio.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "scancodeio.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      initContainers:
        - name: wait-for-postgres
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            - name: SCANCODEIO_DB_NAME
              valueFrom:
                secretKeyRef:
                  key: database
                  name: scancode-secret
            - name: SCANCODEIO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: scancode-secret
            - name: SCANCODEIO_DB_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: scancode-secret
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: SECRET_KEY
                  name: scancode-secret
            - name: SCANCODEIO_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: SCANCODEIO_REDIS_PASSWORD
                  name: scancode-secret
          envFrom:
            - configMapRef:
                name: {{ include "scancodeio.fullname" . }}-scancode-env
          command:
            - sh
            - -c
            - "./manage.py wait_for_database && \
               ./manage.py migrate"
      containers:
        - name: {{ .Chart.Name }}
          args:
            - sh
            - -c
            - "./manage.py collectstatic --no-input --verbosity 0 --clear && \
               gunicorn scancodeio.wsgi:application --bind :{{ .Values.web.port  }} --timeout 600 --workers 8"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.web.port  }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: {{ .Values.web.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.web.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.web.livenessProbe.failureThreshold }}
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: {{ .Values.web.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.web.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.web.readinessProbe.failureThreshold }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
          env:
            - name: SCANCODEIO_DB_NAME
              valueFrom:
                secretKeyRef:
                  key: database
                  name: scancode-secret
            - name: SCANCODEIO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: scancode-secret
            - name: SCANCODEIO_DB_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: scancode-secret
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: SECRET_KEY
                  name: scancode-secret
            - name: SCANCODEIO_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: SCANCODEIO_REDIS_PASSWORD
                  name: scancode-secret
          envFrom:
            - configMapRef:
                name: {{ include "scancodeio.fullname" . }}-scancode-env
          volumeMounts:
            - mountPath: /etc/scancodeio/
              name: {{ include "scancodeio.fullname" . }}-web-claim
            - mountPath: /var/scancodeio/workspace/
              name: {{ include "scancodeio.fullname" . }}-workspace-claim
      restartPolicy: Always
      volumes:
        - name: {{ include "scancodeio.fullname" . }}-web-claim
          persistentVolumeClaim:
            claimName: {{ include "scancodeio.fullname" . }}-web-claim
        - name: {{ include "scancodeio.fullname" . }}-workspace-claim
          persistentVolumeClaim:
            claimName: {{ include "scancodeio.fullname" . }}-workspace-claim
    {{- with .Values.web.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.web.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.web.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
