---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "scancodeio.labels" . | nindent 4 }}
    app: {{ include "scancodeio.fullname" . }}-nginx
  name: scancodeio-nginx
data:
  server-block.conf: |-
    server {
      listen 0.0.0.0:8080;
      root /app;
      location / {
        proxy_pass http://{{- template "scancodeio.fullname" . }}-web.{{- .Release.Namespace }}.svc.{{ .Values.clusterZone }}:{{ .Values.web.service.port }}/;
        proxy_redirect off;
        client_max_body_size 10G;
        proxy_read_timeout 600s;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host:$server_port;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
      }

      location /static/admin/ {
        alias /static/scancodeio-static/static/admin/;
      }
      location /static/rest_framework {
        alias /static/scancodeio-static/static/rest_framework;
      }
      location /static/ {
        alias /static/scancodeio/static/;
      }
      location /status {
        stub_status on;
        access_log off;
        allow 127.0.0.1;
        deny all;
      }
    }


