---
apiVersion: v1
kind: Secret
metadata:
  name: scancode-secret
  labels:
    {{- include "scancodeio.labels" . | nindent 4 }}
type: Opaque
stringData:
  database: {{- include "scancodeio.scancode-database" . | nindent 4 }}
  username: {{- include "scancodeio.scancode-username" . | nindent 4 }}
  password: {{- include "scancodeio.scancode-password" . | nindent 4 }}
  postgres-password: {{- include "scancodeio.scancode-postgres-password" . | nindent 4 }}
  SECRET_KEY: {{- include "scancodeio.scancode-SECRET_KEY" . | nindent 4 }}
  SCANCODEIO_REDIS_PASSWORD: {{- include "scancodeio.scancode-SCANCODEIO_REDIS_PASSWORD" . | nindent 4 }}
