---
apiVersion: v1
kind: Secret
metadata:
  name: scancode-secret
  labels:
    {{- include "scancodeio.labels" . | nindent 4 }}
type: Opaque
stringData:
  database: {{- include "scancodeio.database" . | nindent 4 }}
  username: {{- include "scancodeio.username" . | nindent 4 }}
  password: {{- include "scancodeio.password" . | nindent 4 }}
  postgres-password: {{- include "scancodeio.postgres-password" . | nindent 4 }}
  SECRET_KEY: {{- include "scancodeio.SECRET_KEY" . | nindent 4 }}
  SCANCODEIO_REDIS_PASSWORD: {{- include "scancodeio.SCANCODEIO_REDIS_PASSWORD" . | nindent 4 }}
